Fix yaml parsing on tutorial file
It was previously causing an error when you try to source it:

```
"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
unidentified alias "Source*" at line 2, column 16:
    title: *Source* Plugin
                   ^/Users/tesseralis/Code/gatsby/www/.cache/gatsby-source-git/docs-id/docs/tutorial/part-five/index.md: unidentified alias "Source*" at line 2, column 16:
    title: *Source* Plugin
                   ^
  YAMLException: unidentified alias "Source*" at line 2, co  lumn 16:
      title: *Source* Plugin
                     ^
```